CC = g++

SHELL=C:/Windows/System64/cmd.exe

EXECUTABLE = proga.exe

CFLAGS = -c -Wshadow -Winit-self -Wredundant-decls -Wcast-align -Wundef -Wfloat-equal -Winline -Wunreachable-code -Wmissing-declarations -Wmissing-include-dirs -Wswitch-enum -Wswitch-default -Weffc++ -Wmain -Wextra -Wall -g -pipe -fexceptions -Wcast-qual -Wconversion -Wctor-dtor-privacy -Wempty-body -Wformat-security -Wformat=2 -Wignored-qualifiers -Wlogical-op -Wno-missing-field-initializers -Wnon-virtual-dtor -Woverloaded-virtual -Wpointer-arith -Wsign-promo -Wstack-usage=8192 -Wstrict-aliasing -Wstrict-null-sentinel -Wtype-limits -Wwrite-strings -Werror=vla -D_DEBUG -D_EJUDGE_CLIENT_SIDE

start: main.o inout.o destructor.o
	$(CC) main.o inout.o destructor.o -o $(EXECUTABLE)

main.o:
	$(CC) main.cpp $(CFLAGS)

inout.o:
	$(CC) inout.cpp $(CFLAGS)

destructor.o:
	$(CC) destructor.cpp $(CFLAGS)

clean:
	erase D:\Study\C\Onegin\*.o

run: 
	D:/Study/C/Onegin/$(EXECUTABLE)